apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-config
  namespace: lms
data:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: library_db
  DB_USER: root
  # API endpoint for the React frontend to communicate with (will resolve to the ingress host or cluster service)
  VITE_API_URL: "http://lms.local/api"
